#!/bin/sh

if [ "$M2_REPO" = "" ]; then
    if [ ! -d $HOME/.m2/repository ]; then
        echo "$M2_REPO does not exist. Exiting."
        exit 1
    fi
    export M2_REPO=$HOME/.m2/repository
fi

export PROTOBUF_LIB=$M2_REPO/com/google/protobuf/protobuf-java/3.0.0-beta-2/protobuf-java-3.0.0-beta-2.jar
export JNATS_LIB=$M2_REPO/io/nats/jnats/0.4.0/jnats-0.4.0.jar
export SLF4J_API_LIB=$M2_REPO/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
export SLF4J_SIMPLE_LIB=$M2_REPO/org/slf4j/slf4j-simple/1.7.7/slf4j-simple-1.7.7.jar

export CLASSPATH=target/classes:$PROTOBUF_LIB:$JNATS_LIB:$SLF4J_API_LIB:$SLF4J_SIMPLE_LIB

java -cp $CLASSPATH io.nats.streaming.examples.Publisher $*
